# -*- coding: utf-8 -*-
"""fibonacci.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1t-x8y-irvuJ88Ykzzj5icBo-8UczgzTe
"""

#function fibonaci series
from typing import List
def fibonacci(n):
    sequence = []
    a, b = 0, 1
    for i in range(n):
        sequence.append(a)
        a, b = b, a + b
    return sequence
term = int(input("Enter the number of terms: "))
c = fibonacci(term)
print(c)

