# -*- coding: utf-8 -*-
"""formatted string.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1t-x8y-irvuJ88Ykzzj5icBo-8UczgzTe
"""

#formatted string example
a=23
b=33
c=22
print(f"value of {a}value of {b} value of{c}")
print(f"""
value of {a}value of {b} value of{c}"""
)