# -*- coding: utf-8 -*-
"""oops1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qs2EzRR-dZSryVuk5tYDmFytuKw3CoQD
"""

#create a class for a Bank Account
class BankAccount:
    def __init__(self, balance=0):
        self.balance = balance
    def deposite(self,amount):
      self.amount=amount
      self.balance+=self.amount
      print(f"deposite{self.balance}")
    def withdraw(self,amount):
      self.amount=amount
      if self.amount<self.balance:
       self.balance-=self.amount
       print(f"withdraw {self.balance}")
      else:
        print("insufficient balance")
obj=BankAccount(41234)
obj.deposite(1000)
obj.withdraw(500)