# -*- coding: utf-8 -*-
"""radians.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1D1mQjZ0ZJMp_qurbBKAHYNE413C2WVpR
"""

import math
angle = float(input("enter the angle in degree"))
radian=math.radians(angle)
print("sin of angle",math.sin(radian))
print("cos",math.cos(radian))